### ISSUE TITLE
Add temporal data exercises

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stats19#107]
Very simple, with just a vector of 3 datetime elements will be enough. Heads-up @agila5.

**Comment by agila5** [comment]
A few ideas to begin with: 

We can use R to work also with dates and time units. For example, the functions `Sys.time()` and `date()` are used to show the current date. You can use also the function `strptime()` to extract a date from a character vector, i.e.
``` r
strptime("11/10/2019", format = "%d/%m/%Y")
#> [1] "2019-10-11 BST"
```
The `format` argument specify how the date is stored in the character vector. You can read many details at the help page of that function. 

Exercises: Extract the date component from the following objects (you should guess the appropriate format)
``` r
x <- c("25-12-1991", "08-08-1992", "10-11-2000")
y <- c("12/31/1995", "02/25/1892", "01/31/1900")
z <- c("09091993", "01011900", "08081991")
w <- c("01 January 1901", "02 February 1902", "03 March 1903")

# solution
strptime(x, "%d-%m-%Y")
#> [1] "1991-12-25 UTC" "1992-08-08 UTC" "2000-11-10 UTC"
strptime(y, "%m/%d/%Y")
#> [1] "1995-12-31 UTC" "1892-02-25 UTC" "1900-01-31 UTC"
strptime(z, "%d%m%Y")
#> [1] "1993-09-09 UTC" "1900-01-01 UTC" "1991-08-08 UTC"
strptime(w, "%d %B %Y")
#> [1] "1901-01-01 UTC" "1902-02-02 UTC" "1903-03-03 UTC"
```

**Comment by Robinlovelace** [comment]
Hey @agila5 that looks good but I think it should be a bonus exercise. I think the first thing should be two give them vectors of date, time and datetime, and ask them to subset and change them (e.g. + 1 day/hour/minute). I've just updated the exercises and think it's coming together, can you try them here: https://github.com/ropensci/stats19/releases/download/1.0.0/stats-19-exercises.pdf

Any comments / suggested changes to that very welcome. Thanks!

**Comment by Robinlovelace** [comment]
Done thanks to @agila5 , just taking a look but closing for now as done :+1:
