### ISSUE TITLE
Notes on exercises

### ISSUE THREAD

**Issue by agila5** [ropensci/stats19#108]
Some notes on the exercises. Tomorrow I will continue with the Spatial data analysis section and the temporal data exercises. I created also a PR with some suggestions but, of course, feel free to ignore them. 

1. In my opinion, using the `vignette` function with no argument as in 
https://github.com/ropensci/stats19/blob/a0c4b13e1f21324e07128223b7058604095c5561/inst/stats-19-exercises.Rmd#L192
it's pretty useless since it shows every vignette in every package which is really confusing. I think we should modify it and use `vignette(package = *"package_name"*)` to show all vignette in a package and, then, choose just one topic. 

2. In the Global Environmnent section, 
https://github.com/ropensci/stats19/blob/a0c4b13e1f21324e07128223b7058604095c5561/inst/stats-19-exercises.Rmd#L217
we could write that it's possible also to use `rm(list=ls())` to clear all objects in the global environment, underlying that this does not imply that you have created a new, clear R session (i.e. [here](https://twitter.com/hadleywickham/status/940021008764846080), [here](https://www.tidyverse.org/articles/2017/12/workflow-vs-script/) and [here](https://reprex.tidyverse.org/) with the funny image)

3. Why do you use 
https://github.com/ropensci/stats19/blob/a0c4b13e1f21324e07128223b7058604095c5561/inst/stats-19-exercises.Rmd#L361
https://github.com/ropensci/stats19/blob/a0c4b13e1f21324e07128223b7058604095c5561/inst/stats-19-exercises.Rmd#L403
https://github.com/ropensci/stats19/blob/a0c4b13e1f21324e07128223b7058604095c5561/inst/stats-19-exercises.Rmd#L413
when you have already loaded those packages at the beginning of the script? I know that you set eval=FALSE for that code chunk but it may seem confusing. 

4. Why you use group_by here
https://github.com/ropensci/stats19/blob/a0c4b13e1f21324e07128223b7058604095c5561/inst/stats-19-exercises.Rmd#L486
instead of filter? With the group by it may seem confusing since the two proportions of people shown in the result do not sum to one. This is obvious because the "ratio" of the the proportions is not the same but it may not be so obvious for someone that has just started with these things.

**Comment by Robinlovelace** [comment]
Hi @agila5 thanks for great set of suggestions. Can discuss tomorrow starting with this:

>  I think we should modify it and use vignette(package = *"package_name"*)

I fully agree :+1:

**Comment by Robinlovelace** [comment]
Second question is addressed here:

https://github.com/ropensci/stats19/blob/a4c9472779a6ec23190e21945451a227693dee97/inst/stats-19-exercises.Rmd#L242

**Comment by Robinlovelace** [comment]
> I know that you set eval=FALSE for that code chunk but it may seem confusing.

Good question. I think the +s of loading the packages twice (once to check that the pre-reqs and installed, and again to emphasise the fact that the following example will use a new package) outweigh the -s of potential confusion. In other words, better safe than sorry!

**Comment by Robinlovelace** [comment]
Regarding point 4, I agree. Will change that.
