### ISSUE TITLE
Add new functionality - APIs

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stats19#114]
Add API key, add VRMs, returns data frame of vehicle descriptions plus MOT vars.

Thanks to @ivowengraf for suggestion.

**Comment by Robinlovelace** [comment]
@wengraf rather.

**Comment by layik** [comment]
I am not following this one. Have we got some new API for STATS19? Thanks

**Comment by Robinlovelace** [comment]
Ivo has a plan to get more info on vehicles... In his court, to discuss in London later this week.

**Comment by wengraf** [comment]
This would be a function with a list of number plates as the input, and a data frame of safety-relevant variables derived from the DVSA MOT API as the output  The DVSA MOT API provides vehicle description and MOT history.  It requires an API key (and isn't an open data set), but it is likely to prove useful to professional users with access at work to raw CRASH (note the all caps) vehicle data.  This could be used to determine road-worthiness/legality at the time of the crash and things like engine displacement (which is often messed up in current CRASH output).

**Comment by Robinlovelace** [comment]
As discussed with @wengraf today, the plan is to get this function in by the next submission. PR welcome, suggest the code defining the function lives in `R/mot.R`.

**Comment by wengraf** [comment]
@Robinlovelace & @mem48 : any idea on how the MOT API handles kilometre odometer measurements?  Miles is "mi", so I'm guessing KM is "km".  I've not been lucky enough to see a km one come up yet....

**Comment by Robinlovelace** [comment]
I've no idea I'm afraid Ivo. Malcolm may know...

**Comment by wengraf** [comment]
OK.  I've got a working function done.  Just waiting on comments from RSA and Anneka at TRL on the output, and confirmation that km is "km"...

**Comment by Robinlovelace** [comment]
Cannot think what else it could be so see no reason in assuming that for now. Good plan to pass it by others before the PR though, looking forward to giving it a spin 🚗 👍

**Comment by mem48** [comment]
I'm not sure on mi/km issue, I'll search the data, I also have some api docs I can share.

**Comment by mem48** [comment]
```
> table(tests$odometerUnit)

       km        mi 
   602117 152127508 
```

**Comment by mem48** [comment]
[MOT_user_guide_v4.docx](https://github.com/ropensci/stats19/files/3766615/MOT_user_guide_v4.docx)

**Comment by Robinlovelace** [comment]
Good digging. What do the numbers above mean though?

**Comment by wengraf** [comment]
Thanks @mem48 - I guessed right.  At the moment I'm converting everything to miles.

**Comment by wengraf** [comment]
Pull request submitted - and I had it checked out by the chaps at RSA.  Bruce suggested (alongside existing test count and test pass count) a count of "passes with advisories" (which are basically borderline passes, a subset of passes).

**Comment by Robinlovelace** [comment]
Great, many thanks for #121 Ivo, looking good. We can always tidy up after merging but will leave it open for further changes and comments for now.

**Comment by layik** [comment]
OK. I guess I can start writing some tests without an API key, but I think we can add one to the Travis instance. I guess I will have to create one for the repo.

**Comment by layik** [comment]
Apologies for late replies/input.

**Comment by layik** [comment]
Great, saves me doing it. Is it added on Travis? I could do that bit.

**Comment by Robinlovelace** [comment]
OK sure, will share. BTW, in other news, I suggest we keep this issue open to discuss adding functions that interface with DfT's in progress stats19 API. Heads-up also @h-bougdah, we discussed this today and mentioned the possibility of doing a mini hackathon on it.

**Comment by layik** [comment]
Great work Robin.

**Comment by wengraf** [comment]
> > I guess I will have to create one for the repo.
> 
> One to discuss. Note that https://dvsa.github.io/mot-history-api-documentation/ provides only one key per institute, so may be worth sharing the ITS one.

Is sharing a key a good idea?  Suspect this is a no-no for DVSA.
