### ISSUE TITLE
Move stats-19-exercises.Rmd into the stats19-training vignette

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stats19#117]

**Comment by layik** [comment]
Alright, I better get back in here at some point. Just pulled the latest and will focus on writing tests but see if I can help here/elsewhere too.

**Comment by Robinlovelace** [comment]
Thanks @layik, sadly coverage is now below 70% :( so new tests, yes please :+1: On this issue, was thinking the content in https://github.com/ropensci/stats19/blob/master/inst/stats-19-exercises.Rmd would be more accessible if it were merged into the currently tiny exercises vignette https://github.com/ropensci/stats19/blob/master/vignettes/stats19-training.Rmd
