### ISSUE TITLE
Where to get OSM roads layer for other areas?

### ISSUE THREAD

**Issue by WillSERP** [ropensci/stats19#125]
I am trying to produce a map of Essex with roads coloured to show relative collision frequency. Following the examples from the course I have got the roads key download for the Isle of Wight, 

#download roads OSM layer.... need layer for essex as this is for Isle of Wight!
u = "https://github.com/ropensci/stats19/releases/download/1.1.0/roads_key.Rds"

....but I need to download OSM roads data for Essex. Does anyone know how I can download this data?

**Comment by Robinlovelace** [comment]
Sure, using the in-development geofabric package you can download large chunks of OSM data. Reproducible example below, let us know if you have any issues with this. Heads-up @agila5 who has helped out with this.

``` r
# Aim: demonstrate how to get OSM data representing regional road networks

remotes::install_github("itsleeds/geofabric")
#> Skipping install of 'geofabric' from a github remote, the SHA1 (947c1863) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(geofabric)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

region_name = "essex"
osm_data = get_geofabric(name = region_name)
#> No exact matching geofabric zone. Best match is Essex (34.2 MB)
#> Downloading http://download.geofabrik.de/europe/great-britain/england/essex-latest.osm.pbf to 
#> /tmp/Rtmptvguw7/essex.osm.pbf
#> Old attributes: attributes=name,highway,waterway,aerialway,barrier,man_made
#> New attributes: attributes=name,highway,waterway,aerialway,barrier,man_made,maxspeed,oneway,building,surface,landuse,natural,start_date,wall,service,lanes,layer,tracktype,bridge,foot,bicycle,lit,railway,footway
#> Using ini file that can can be edited with file.edit(/tmp/Rtmptvguw7/ini_new.ini)
head(osm_data)
#> Simple feature collection with 6 features and 27 fields
#> geometry type:  LINESTRING
#> dimension:      XY
#> bbox:           xmin: -0.0101305 ymin: 51.45926 xmax: 0.2673947 ymax: 51.68909
#> epsg (SRID):    4326
#> proj4string:    +proj=longlat +datum=WGS84 +no_defs
#> # A tibble: 6 x 28
#>   osm_id name  highway waterway aerialway barrier man_made maxspeed oneway
#>   <chr>  <chr> <chr>   <chr>    <chr>     <chr>   <chr>    <chr>    <chr> 
#> 1 14416… <NA>  motorw… <NA>     <NA>      <NA>    <NA>     70 mph   yes   
#> 2 18811… <NA>  motorw… <NA>     <NA>      <NA>    <NA>     70 mph   yes   
#> 3 18811… <NA>  motorw… <NA>     <NA>      <NA>    <NA>     70 mph   yes   
#> 4 18811… <NA>  motorw… <NA>     <NA>      <NA>    <NA>     70 mph   yes   
#> 5 18811… Dart… trunk   <NA>     <NA>      <NA>    <NA>     50 mph   yes   
#> 6 18811… <NA>  trunk   <NA>     <NA>      <NA>    <NA>     70 mph   yes   
#> # … with 19 more variables: building <chr>, surface <chr>, landuse <chr>,
#> #   natural <chr>, start_date <chr>, wall <chr>, service <chr>,
#> #   lanes <chr>, layer <chr>, tracktype <chr>, bridge <chr>, foot <chr>,
#> #   bicycle <chr>, lit <chr>, railway <chr>, footway <chr>, z_order <int>,
#> #   other_tags <chr>, geometry <LINESTRING [°]>
head(osm_data$geometry)
#> Geometry set for 6 features 
#> geometry type:  LINESTRING
#> dimension:      XY
#> bbox:           xmin: -0.0101305 ymin: 51.45926 xmax: 0.2673947 ymax: 51.68909
#> epsg (SRID):    4326
#> proj4string:    +proj=longlat +datum=WGS84 +no_defs
#> First 5 geometries:
#> LINESTRING (0.0969445 51.68909, 0.097476 51.688...
#> LINESTRING (0.0132489 51.67922, 0.0104745 51.67...
#> LINESTRING (0.1275181 51.67896, 0.1265679 51.67...
#> LINESTRING (0.2565658 51.61386, 0.256402 51.614...
#> LINESTRING (0.2517381 51.45926, 0.2526332 51.45...
table(osm_data$highway)
#> 
#>      bridleway          byway   construction       cycleway        footway 
#>            782              1            213           2171          24336 
#>  living_street       motorway  motorway_link             no           path 
#>            108            227            123              9           3106 
#>     pedestrian        primary   primary_link       proposed        raceway 
#>            316           2715             89             19              4 
#>    residential           road      secondary secondary_link        service 
#>          27209             22           2771             13          32117 
#>          steps       tertiary  tertiary_link          track          trunk 
#>            947           5374             47           4483           1501 
#>     trunk_link   unclassified 
#>            412           5644
motorways = osm_data[osm_data$highway == "motorway", ]
motorways = osm_data %>% 
  filter(highway == "motorway")
mapview::mapview(motorways)
```

![](https://i.imgur.com/tSYfyxO.png)

<sup>Created on 2019-10-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Any comments/suggestions very welcome, hope it helps.

**Comment by WillSERP** [comment]
Many thanks Robin, however I get the following error after running the first two lines (also, sorry I can't remember how to make the reproducible example format). This is the output I see in the console:

> remotes::install_github("itsleeds/geofabric")
Downloading GitHub repo itsleeds/geofabric@master
Installing 1 packages: classInt
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/classInt_0.4-2.zip'
Content type 'application/zip' length 90285 bytes (88 KB)
downloaded 88 KB

package ‘classInt’ successfully unpacked and MD5 sums checked
Error: Failed to install 'geofabric' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘classInt’
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
> library(geofabric)
Error in library(geofabric) : there is no package called ‘geofabric’

**Comment by Robinlovelace** [comment]
I think you need to uninstall and reinstall the classInt package. Try restarting the session with Ctl+Shift+F10 or just restarting RStudio.

**Comment by Robinlovelace** [comment]
And, as a quick fix, I've uploaded the OSM road network data for Essex which you can download from here: https://github.com/ropensci/stats19/releases/download/1.1.0/osm_lines_data_essex.Rds

**Comment by WillSERP** [comment]
Many thanks, restarting has fixed the problem. Will see how I get on when I can return to it later in the week.

**Comment by agila5** [comment]
btw, if you are interested in replicating something similar to the last map in the pdf document of the course, I'm working on an update version of the iow_example.R file. It doesn't really fit in the stats19 repo but I can still share it when it's finished if you're interested in that approach.
