### ISSUE TITLE
Counting collisions on road links

### ISSUE THREAD

**Issue by WillSERP** [ropensci/stats19#126]
I have the following code that plots a 30m wide polygon around each road segment with collisions plotted on top. I want to plot each road segment with a key to indicate collision count on each segment. I've been trying to use the aggregate function from https://geocompr.robinlovelace.net/spatial-operations.html#spatial-vec (4.2.5) but have not been getting anywhere.

library(tidyverse)
library(sf)
library(tmap)
tmap_mode("plot")
library(stats19)
library(mapview)

#import CRASH data from csv
crash <- read.csv("C:/Users/william.cubbin/Desktop/R-training/Routes/CRASH.csv", header = TRUE)

# remove misplotted data falling outside of box drawn around Essex
crash_map = filter (crash, Grid.Reference..Easting. > 530000 &  Grid.Reference..Easting. < 630000  
                    &  Grid.Reference..Northing. > 170000   &  Grid.Reference..Northing. < 250000)

#Set coordinate format to eastings and northings 
crash_map = st_as_sf (crash_map, coords = c("Grid.Reference..Easting.", "Grid.Reference..Northing."), crs = 27700 )

#get osm data
remotes::install_github("itsleeds/geofabric")
library(geofabric)
library(dplyr)
region_name = "essex"
osm_data = get_geofabric(name = region_name)
head(osm_data)
head(osm_data$geometry)
table(osm_data$highway)

# define roads to plot from osm data
roads = osm_data %>% 
  filter(highway %in% c("motorway", "primary", "secondary", "tertiary", 
                        "motorway_link", "primary_link", "secondary_link", "tertiary_link"))

#convert roads to osgb format
roads_osgb = st_transform(roads, 27700)

#create 30m buffer around roads_osgb
polyroads = st_buffer(roads_osgb, dist = 30)

# plot map of roads by type and dot map of collisions by severity
mapview::mapview(crash_map[ , 4]) + mapview::mapview(polyroads[ , 3])

**Comment by Robinlovelace** [comment]
Great question @WillSERP, thanks for the reproducible example. Will aim to take a look next week. Heads-up @layik and @agila5 and @mem48 who may also be able to help with this.

**Comment by agila5** [comment]
Can you share the CSV file?

**Comment by WillSERP** [comment]
Attached as .txt as .csv not supported. 
[CRASH.txt](https://github.com/ropensci/stats19/files/3794874/CRASH.txt)

**Comment by agila5** [comment]
I would do something like the following reprex. Please note that I added some notes and comments.  
``` r
# packages
library(tidyverse)
library(janitor)
#> 
#> Attaching package: 'janitor'
#> The following objects are masked from 'package:stats':
#> 
#>     chisq.test, fisher.test
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3
library(geofabric)
library(tmap)

# import data from txt
crashes <- read_delim(
  file = "C:/Users/Utente/Downloads/CRASH.txt",
  delim = "\t",
  escape_double = FALSE,
  col_types = cols(
    `Collision Time` = col_character()
  ),
  trim_ws = TRUE
)
# A few notes here: 
# 1) there are some errors in your .txt file since you cannot specify a Time
# variable as, for example, 13:20:PM (as in the third row of the .txt file). If
# you explicitly add AM/PM then the range of the hours component should be
# 01-12. You can read more details in the help page of ?strptime (search for %p
# and %I) and in the Chapter 16 of the R for Data Science (R4DS) book.
# https://r4ds.had.co.nz/dates-and-times.html.
# 2) I prefer to use readr functions (like read_delim) to import data into R.
# You can read more details about that in Chapter 11 of R4DS:
# https://r4ds.had.co.nz/data-import.html
# You can get something similar using read.delim function. 
# 3) In my opinion you should always avoid spaces in the variable names. For
# example creating a variable called "Collision Time" makes the code
# unnecessarily complicated since R cannot distinguish between spaces in names
# and spaces in code which implies that you must use backticks to surround
# variable names with spaces as in `Collision Time`. You should prefer something
# like "collision_time" (i.e. snake_case) or "collisionTime" (lower Camel case).
# For this reason I use the function clean_names to change all spaces to "_"

# fix names
crashes <- clean_names(crashes)

# remove misplotted data
crashes <- crashes %>% 
  filter(
    grid_reference_easting > 530000, grid_reference_easting < 630000, 
    grid_reference_northing > 170000, grid_reference_northing < 250000
  )
# I'm not sure if you noticed that, but this filtering does not exclude any
# point.

# transform to sf
crashes_sf <- st_as_sf(
  x = crashes, 
  coords = c("grid_reference_easting", "grid_reference_northing"), 
  crs = 27700
)

# download roads data
geofabric_data <- get_geofabric("essex") %>% st_transform(crs = 27700)
#> No exact matching geofabric zone. Best match is Essex (34.2 MB)
#> Downloading http://download.geofabrik.de/europe/great-britain/england/essex-latest.osm.pbf to 
#> C:\Users\Utente\AppData\Local\Temp\RtmpkdIS8c/essex.osm.pbf
#> Old attributes: attributes=name,highway,waterway,aerialway,barrier,man_made
#> New attributes: attributes=name,highway,waterway,aerialway,barrier,man_made,maxspeed,oneway,building,surface,landuse,natural,start_date,wall,service,lanes,layer,tracktype,bridge,foot,bicycle,lit,railway,footway
#> Using ini file that can can be edited with file.edit(C:\Users\Utente\AppData\Local\Temp\RtmpkdIS8c/ini_new.ini)
roads <- geofabric_data %>%
  filter(highway %in% c(
    "motorway", "primary", "secondary", "tertiary",
    "motorway_link", "primary_link", "secondary_link", "tertiary_link"
  ))

# plot
tm_shape(roads) + 
  tm_lines(col = "highway") + 
tm_shape(crashes_sf) + 
  tm_dots() + 
  tm_layout(legend.outside = TRUE)
```

![](https://i.imgur.com/t9v2dZq.png)

``` r

# create buffer
roads_buffer <- st_buffer(roads, 30)

# for obvious reasons there are a lot of intersections between the buffers (just
# look at mapview::mapview(roads_buffer)) that could inflate the number of
# crashes. You should read ?st_buffer and
# https://postgis.net/docs/ST_Buffer.html for more details on how to create
# buffers.

# intersections between crashes and roads buffer
roads_buffer_and_crashes_intersections <- st_intersects(crashes_sf, roads_buffer)
roads_buffer_and_crashes_intersections
#> Sparse geometry binary predicate list of length 6119, where the predicate was `intersects'
#> first 10 elements:
#>  1: 9011
#>  2: 1306
#>  3: 4169
#>  4: 8891
#>  5: 9782
#>  6: 3149, 3150, 4172, 4284, 10983, 10984
#>  7: 802
#>  8: 6906, 7111, 7122, 10482
#>  9: (empty)
#>  10: (empty)

# You should read it as follows: the first crashes occurred in the buffer of the
# 9011th road, the second crashes occurred in the buffer of the 1306 road and so
# on. The sixth buffer occurred in the intersection of the buffers of the 3149,
# 3150, 4172, 4284, 10983 and 10984 roads.

# That's an object of class Sparse Geometry Binary Predicate and we have to
# slightly modify it to obtain the number of crashes for each road's buffer. The
# following code is slightly technical but I can explain it if you want.

roads_buffer_and_crashes_intersections <- roads_buffer_and_crashes_intersections %>% 
  unlist() %>% factor(levels = seq_len(nrow(roads_buffer))) %>% table()

# This is the result
head(roads_buffer_and_crashes_intersections, 10)
#> .
#>  1  2  3  4  5  6  7  8  9 10 
#>  4  8  2  7  1  2  0  0  2  3

# Four car accidents occurred in the first road buffer, eight crashes occurred
# in the second road, in the 7th road buffer there was no crash and so on.

# Now we add this information to the previous plot
roads$roads_buffer_and_crashes_intersections <- roads_buffer_and_crashes_intersections

tm_shape(roads) + 
  tm_lines(col = "roads_buffer_and_crashes_intersections", 
           palette = "viridis", breaks = c(0, 1, 3, 5, Inf), 
           labels = c("No crashes", "One or two crashes", "Three or four", "Five or more")) + 
tm_shape(crashes_sf) + 
  tm_dots() + 
tm_layout(legend.outside = TRUE)
```

![](https://i.imgur.com/fCjLstx.png)

<sup>Created on 2019-11-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by WillSERP** [comment]
Many thanks for your help Andrea, I look forward to working through this next week - lots for me to learn there.

**Comment by mem48** [comment]
@WillSERP have a look at the crash layers in www.cyipt.bike. We have done something similar, the data is free to download and the code is open.

**Comment by Robinlovelace** [comment]
Great solution @agila5 you are on fire :fire: (in a good way!). One question: why use this instead of `aggregate()` or `summarise()` functions?

```
roads_buffer_and_crashes_intersections <- roads_buffer_and_crashes_intersections %>% 
  unlist() %>% factor(levels = seq_len(nrow(roads_buffer))) %>% table()

# This is the result
head(roads_buffer_and_crashes_intersections, 10)
#> .
#>  1  2  3  4  5  6  7  8  9 10 
#>  4  8  2  7  1  2  0  0  2  3

# Four car accidents occurred in the first road buffer, eight crashes occurred
# in the second road, in the 7th road buffer there was no crash and so on.

# Now we add this information to the previous plot
roads$roads_buffer_and_crashes_intersections <- roads_buffer_and_crashes_intersections
```

I suspect `st_join -> group_by -> summarise` or simply `aggregate(crashes, road_buffers)` would be more concise and easier to understand but arrive at a similar result, but may be missing something...

Relevant part of #geocompr: https://geocompr.robinlovelace.net/spatial-operations.html#spatial-aggr

**Comment by agila5** [comment]
> One question: why use this instead of aggregate() or summarise() functions?

Because I forgot about those functions 😪
 
Anyway, maybe it's obvious but I still don't get how to use aggregate or summarize in that case. Help? The problem is that I don't want to apply any FUN to the data but count the occurrences and put 0 in every road that does not intersect any point.

**Comment by agila5** [comment]
Just for fun I did a little testing and I think I understand now how to solve the same problem using `summarize` (but not with aggregate), i.e.
``` r
st_join(roads_buffer, crashes_sf) %>%
  st_drop_geometry() %>% # I just need to count the rows, I don't need the geometry structure
  group_by(as.numeric(osm_id)) %>% # problem 1
  summarise(n = sum(!is.na(collision_report_id))) %>% # problem 2
  pull(n) %>% 
  head(10)
#>  [1] 4 8 2 7 1 2 0 0 2 3
```

In my opinions there are a few problems with that code: 

1. I had to set `as.numeric(osm_id)` otherwise `group_by `+ `summarize `would have changed che order of the road's buffer (more details https://github.com/tidyverse/dplyr/issues/2159 and https://github.com/tidyverse/dplyr/issues/3279 but I don't fully understand those issues). 
2. After the spatial left join each road's buffer where no car crashes occurred is linked with "empty rows". This means that the collision_report_id column after the join has NA value for all "empty" road's buffer (where no car crashes occurred). So I summed the number of non-NA collision_report_id to count the number of crashes in each buffer. The problem here is that this approach doesn't work if there are NA in the original collision_report_id column (Even if it doesn't make sense to have NA in an ID column but that's a separate problem). 

One minor problem is that the st_join approach is slighly slower than the old one even if it's probably less obscure. 

``` r
library(microbenchmark)  
res <- microbenchmark(
  with_factor = {st_intersects(crashes_sf, roads_buffer) %>% 
      unlist() %>% factor(levels = seq_len(nrow(roads_buffer))) %>% 
      table() %>% as.numeric()}, 
  with_join = {st_join(roads_buffer, crashes_sf) %>%
      st_drop_geometry() %>% group_by(as.numeric(osm_id)) %>% 
      summarise(n = sum(!is.na(collision_report_id))) %>% pull(n)}, 
  times = 100L, 
  check = "equal"
)

res
#> Unit: milliseconds
#>         expr      min        lq      mean   median        uq      max
#>  with_factor 730.9931  760.4923  799.8387  785.061  804.9679 1293.529
#>    with_join 993.3983 1021.8003 1051.9081 1039.626 1058.9196 1275.931
#>  neval cld
#>    100  a 
#>    100   b
ggplot2::autoplot(res)
```

![](https://i.imgur.com/V1oM8Y9.png)

<sup>Created on 2019-11-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment]
Good to know both approaches work, and interesting that the factor one is faster. Thanks @agila5 !

**Comment by WillSERP** [comment]
@Robinlovelace I have tried the code from @agila5 and I get the same output. I think I understand most of the code but there are bits I don't (this project has the dual purpose of creating something useful for proactive roadside enforcement and helping me learn some R coding). My aim is to make the final plot using mapview so I can create an interactive and shareable html file as the output.

To help me learn I want to keep things as simple as possible, which is why I think the aggregate function is what I need. The code below shows what I have tried based on 4.2.5 in https://geocompr.robinlovelace.net/spatial-operations.html#spatial-vec
.... however I get the error shown in the console output, and then it won't map.

I guess I need some guidance on how to use aggregate for this particular application.

library(tidyverse)
library(sf)
library(tmap)
tmap_mode("plot")
library(stats19)
library(mapview)

#import CRASH data from csv
crash <- read.csv("C:/Users/william.cubbin/Desktop/R-training/Routes/CRASH.csv", header = TRUE)

#Use strptime with %p and %I to convert time field into useable format for analysis
#Further details in chapter 16 of R for data science and https://r4ds.had.co.nz/dates-and-times.html

#remove misplotted data falling outside of box drawn around Essex
crash_map = filter (crash, Grid.Reference..Easting. > 530000 & Grid.Reference..Easting. < 630000
                    & Grid.Reference..Northing. > 170000 & Grid.Reference..Northing. < 250000)

#Set coordinate format to eastings and northings
crash_map = st_as_sf (crash_map, coords = c("Grid.Reference..Easting.", "Grid.Reference..Northing."), crs = 27700 )

#get osm data
remotes::install_github("itsleeds/geofabric")
library(geofabric)
library(dplyr)
region_name = "essex"
osm_data = get_geofabric(name = region_name)
head(osm_data)
head(osm_data$geometry)
table(osm_data$highway)

#define roads to plot from osm data
roads = osm_data %>%
  filter(highway %in% c("motorway", "primary", "secondary", "tertiary", "trunk", 
                        "motorway_link", "primary_link", "secondary_link", "tertiary_link"))

#convert roads to osgb format
roads_osgb = st_transform(roads, 27700)

#create 30m buffer around roads_osgb
polyroads = st_buffer(roads_osgb, dist = 20, endCapStyle = "FLAT", joinStyle = "BEVEL")

#plot map of roads by type and dot map of collisions by severity
##mapview::mapview(crash_map[ , 4]) + mapview::mapview(polyroads[ , 3])

#below is based on nz_avheight = aggregate(x = nz_height, by = nz, FUN = mean) from 4.2.5 in 
#https://geocompr.robinlovelace.net/spatial-operations.html#spatial-vec
#I have determined that nz is analagous to polyroads and nz_height is analagous to crash_map and that...
#...I want a count function rather than a mean function.
#attempted 3 version of this code
crash_roads = aggregate(crash_map, polyroads, FUN = count)
crash_roads = aggregate(x = crash_map, by = polyroads, FUN = count)
crash_roads = aggregate(x = crash_map, by = polyroads, FUN = mean)
warnings()

Console output from last 4 lines.....
> crash_roads = aggregate(crash_map, polyroads, FUN = count)
Error in UseMethod("summarise_") : 
  no applicable method for 'summarise_' applied to an object of class "c('integer', 'numeric')"
> crash_roads = aggregate(x = crash_map, by = polyroads, FUN = count)
Error in UseMethod("summarise_") : 
  no applicable method for 'summarise_' applied to an object of class "c('integer', 'numeric')"
> crash_roads = aggregate(x = crash_map, by = polyroads, FUN = mean)
There were 50 or more warnings (use warnings() to see the first 50)
> warnings()
Warning messages:
1: In mean.default(X[[i]], ...) :
  argument is not numeric or logical: returning NA
2: In mean.default(X[[i]], ...) :
  argument is not numeric or logical: returning NA
3: In mean.default(X[[i]], ...) :
  argument is not numeric or logical: returning NA

**Comment by WillSERP** [comment]
@Robinlovelace @agila5 ... I've found some code that works for me!
polyroads$pt_count <- lengths(st_intersects(polyroads, crash_map))
mapview::mapview(polyroads[ , 29])

This adds a new column called pt_count to my roads buffer table (polyroads) that counts the number of collisions in each polygon. I can then plot polyroads by this column (i.e. column 29) using mapview.

Some work to do now refining the result and formatting the output, but this looks straightforward with plenty of example code to work from.
Thanks both for all your help.

**Comment by agila5** [comment]
> polyroads$pt_count <- lengths(st_intersects(polyroads, crash_map))

I spent two hours on something so simple
🤦‍♂ 

@WillSERP thank you so much!

**Comment by WillSERP** [comment]
> > polyroads$pt_count <- lengths(st_intersects(polyroads, crash_map))
> 
> I spent two hours on something so simple
> 🤦‍♂
> 
> @WillSERP thank you so much!

Your generosity was appreciated and I learned some useful stuff from it. I've now got end caps and buffers in my road polygons to reduce overlap.

**Comment by Robinlovelace** [comment]
> Your generosity was appreciated and I learned some useful stuff from it. I've now got end caps and buffers in my road polygons to reduce overlap.

You read my mind @WillSERP, that was the next thing I was going to say!
