### ISSUE TITLE
NA in MOT odometer unit

### ISSUE THREAD

**Issue by wengraf** [ropensci/stats19#127]
The get_MOT() function currently does conversions from KM odometers into miles.  It is currently failing to handle vehicles where odometer unit is listed as NA.  I will fix this asap.

**Comment by Robinlovelace** [comment]
Thanks for identifying these issues @wengraf, any examples of the types of cars that this fails for in the meantime (did you mention 1994?) welcome.

**Comment by wengraf** [comment]
I'm testing it on a very large 2014 list of VRMs.  First issue I've come across is handling vehicles that have _only_ ever failed.  Now fixed.  Will keep looking....

**Comment by wengraf** [comment]
Actually, this issue a complete misnomer - I think it is actually an issue with non-alphanumeric characters in lists of VRMs.  I've put checks to the vrm list before the API calls to make sure the VRMs look legit.  Checking now to see if that stops problems.

**Comment by wengraf** [comment]
Fix now #128

**Comment by wengraf** [comment]
So far, I've successfully tested on 50k real-world VRMs.  Will try further tests when my API allowance and time both allow.

**Comment by Robinlovelace** [comment]
Is this fixed for you now @wengraf ? If you could provide an example with copy paste of the code and resulting output, that would give me confidence to close this. Cheers.

**Comment by wengraf** [comment]
Sorry, all appears fixed as of my last PR. I’ll keep on testing VRMs, but resolved this issue.
