### ISSUE TITLE
Add link to media and commons library use

### ISSUE THREAD

**Issue by layik** [ropensci/stats19#130]
Package has been [used](https://commonslibrary.parliament.uk/economy-business/transport/roads/constituency-data-traffic-accidents/) by commons library and there is a link to this package. 

Update README accordingly.

**Comment by layik** [comment]
Oh and all the credit to @Robinlovelace for this.

**Comment by Robinlovelace** [comment]
Good thinking Layik.

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/70164249-bf730080-16b8-11ea-96d8-ec92c0b5cc69.png)

**Comment by Robinlovelace** [comment]
Heads-up @layik this is now in the readme, took longer than expected, hopefully worth the effort but not sure...
