### ISSUE TITLE
Hex sticker/logo

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stats19#132]

**Comment by Robinlovelace** [comment]
See here for a starter for 10: https://github.com/ITSLeeds/hexstickers/blob/master/stats19_hexsticker.svg

![image](https://user-images.githubusercontent.com/1825120/70169059-f6014900-16c1-11ea-9866-2e26f830f895.png)

Heads-up @mem48 I think a more sedate logo would be beneficial...

**Comment by mem48** [comment]
I'm open to [suggestions](https://www.google.com/search?hl=en&tbm=isch&source=hp&q=car+crash+logo)

**Comment by layik** [comment]
very late to this party, great effort.

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/72342209-e8c57a00-36c3-11ea-9cac-874fb1c4824a.png)

**Comment by layik** [comment]
Yea, so latest :) red and blue it is!

**Comment by Robinlovelace** [comment]
Hi all, @layik @mem48 @wengraf, @h-bougdah and @WillSERP especially, here is the latest on logos, which do you prefer (1:6)?:

![image](https://user-images.githubusercontent.com/1825120/74765808-2053b300-527c-11ea-9ca7-d38949b08e6b.png)

**Comment by Robinlovelace** [comment]
More discussion: https://twitter.com/robinlovelace/status/1229836482954833920

**Comment by layik** [comment]
Number 4, hiding the cars :)

**Comment by Robinlovelace** [comment]
Heads-up @layik, @agila5, @wengraf, @publichealthdatageek and anyone else using the pkg, here are some more designs:

![image](https://user-images.githubusercontent.com/1825120/75241478-1111bf80-57be-11ea-979f-34ab3433daa9.png)

**Comment by WillSERP** [comment]
The first one is my personal favourite, as it recognises more than one type of road user. If a Road Safety Partnerships had this logo they would stick a helmet on the cyclist though.
I like the simplicity of 2,3,4 from a purely aesthetic perspective.

**Comment by agila5** [comment]
N1

**Comment by Robinlovelace** [comment]
![logo](https://user-images.githubusercontent.com/1825120/75247955-07428900-57cb-11ea-85ea-a43e3e2a3eda.png)


Final logo

**Comment by Robinlovelace** [comment]
![logo-500](https://user-images.githubusercontent.com/1825120/75247979-1590a500-57cb-11ea-84b5-fbc6a8367b4d.png)
![logo-800](https://user-images.githubusercontent.com/1825120/75247981-1590a500-57cb-11ea-9c7d-48988b7c04cc.png)

500 and 800 px versions look awesome!

**Comment by Robinlovelace** [comment]
Finally we can put this to bed: https://github.com/ropensci/stats19/pull/159

**Comment by layik** [comment]
Fantastic choice! Great work @Robinlovelace and our the wizard.

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/75869522-9706b980-5e01-11ea-9fe7-06d83dcde85a.png)
