### ISSUE TITLE
Add output_format argument to get_stats19()

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stats19#134]
I can think of various pros, as it makes the data more usable more quickly without knowing about `format_sf()` but there maybe cons of doing this. To discuss tomorrow.

Heads-up @layik, @mem48, @wengraf, @publichealthgeek and @agila5, seem like a good plan to you?

**Comment by layik** [comment]
I was going to suggest this when I last spent some time playing with the data for my contributory factors min-project/research. So fine by me to add a switch.

**Comment by agila5** [comment]
I don't know all the details of stats19 package but IMO there are two problem:

1) As far as I know it's really easy to convert a data.frame/tibble into a sf object with POINT geometry but the vice versa is not so immediate (i.e. you don't immediately recover the X and Y columns). 
2) Last week I met a few people that use stats19 data in a sp or spatstat framework and, in their case, this change would add an unnecessary complication to their workflow. I know that even if the output is a dataframe they still need to convert it to a SpatialPointDataFrame or ppp object but IMO it feels more natural to work on a data.frame in this case. 

I would keep a dataframe output as a default of get_stats19 but I would:

1) add a message to get_stats19 function that says "You can transform this data into a sf format using format_sf() function" so anybody can read about the format_sf function and (if you agree) add new format_sp() and format_spatstat() functions. 
2) add a new argument to the get_stats19 function that selects the desired output format (i.e one of data.frame, tibble or sf, and maybe sp or spatstat, defaulting to data.frame)

**Comment by Robinlovelace** [comment]
Good feedback, great to know some people are using the outputs with `spatstat`, that is a good reason to not change the default data frame output. Think your suggestion 2) makes most sense @agila5, that way people who want `sf` objects just need to say:

```
get_stats19(2018, "ac", output_format = "sf")
```

making it easier + quicker for people to switch to spatial data analysis as @layik says.

**Comment by Robinlovelace** [comment]
You up for implementing it @agila5 ? I think it could be a '5 liner', not a big change (see updated issue title).

**Comment by wengraf** [comment]
Agree on this:

“add a new argument to the get_stats19 function that selects the desired output format (i.e one of data.frame, tibble or sf, and maybe sp or spatstat, defaulting to data.frame)”

There are just far to many conceivable, valid and common workflows around to think about pushing people down an sf path (much as I would want to).

**Comment by agila5** [comment]
> You up for implementing it @agila5 ? I think it could be a '5 liner', not a big change (see updated issue title).

Yup, but I won't work on this until thursday or friday.
