### ISSUE TITLE
Allow users to set a default directory for data downloads to reduce strain on internet connections and speed up tests

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stats19#141]
I suggest that if a user sets an environment variable, e.g.:

```
STATS19_DOWNLOAD_DIRECTORY=~/data/stats19
```

the package uses that directory, not a random `tempdir()` as the place where it looks for and downloads data, speeding up testing and reducing bandwidth requirements for developers and researchers wanting to store the data.

This has been demonstrated successfully in the `geofabric` data package: https://github.com/ITSLeeds/geofabric/commit/a3c180c119908c079f642cb2bc74ab612455a33c

**Comment by layik** [comment]
Reopen if not sufficient.

**Comment by Robinlovelace** [comment]
Great work @layik, many thanks!
