### ISSUE TITLE
Daylight savings time

### ISSUE THREAD

**Issue by markruddy** [ropensci/stats19#146]
Hi,

I *imagine* that time of accident in stats19 is given as 'local' time ie GMT or BST. But there's no timeszone in the data to confirm that. 

1. Can anyone confirm how daylight savings is handled (if at all) in the dataset.
2. Is there value in adding functionality in `stats19` to derive a `date-time` object with implicit daylight savings information?

**Comment by Robinlovelace** [comment]
Thanks for the issue. Any ideas how BST is encoded in R?

**Comment by markruddy** [comment]
I don't think it's explicitly indicated. Rather it's represented as part of the timezone. [Base R time zones](https://stat.ethz.ch/R-manual/R-devel/library/base/html/timezones.html) use a [timezone database](https://data.iana.org/time-zones/tz-link.html), which implements Daylight Savings Time (DST) rules. 

So for `stats19` I guess this means producing a date-time variable from date and time columns, and tagging this as `tz = 'Europe/London'` (not as complicated as I first imagined). Any conversion from this to 'GMT' or 'UTC' could then be performed in the standard ways by users.

Thinking through this as I go. Happy to have a second opinion on this. If the package were to offer an eg date-time option during import, we'd have to be sure that stats19 data were using local time.

**Comment by Robinlovelace** [comment]
Thanks @markruddy. Would setting the timezone of the data returned by `stats19` solve the problem? Should be a quick fix if so, as shown below, seems to work fine with `lubridate`, the base R way shouldn't be any harder (may even be easier):

``` r
# aim: check timezone of stats19 data
library(stats19)
#> Data provided under OGL v3.0. Cite the source and link to:
#> www.nationalarchives.gov.uk/doc/open-government-licence/version/3/
a = get_stats19(2018)
#> Files identified: dftRoadSafetyData_Accidents_2018.csv
#>    http://data.dft.gov.uk.s3.amazonaws.com/road-accidents-safety-data/dftRoadSafetyData_Accidents_2018.csv
#> Attempt downloading from:
#> Data saved at /tmp/RtmpRBvToc/dftRoadSafetyData_Accidents_2018.csv
#> Reading in:
#> /tmp/RtmpRBvToc/dftRoadSafetyData_Accidents_2018.csv
summary(a$date)
#>                  Min.               1st Qu.                Median 
#> "2018-01-01 00:00:00" "2018-04-10 00:00:00" "2018-07-05 00:00:00" 
#>                  Mean               3rd Qu.                  Max. 
#> "2018-07-05 08:17:56" "2018-10-05 00:00:00" "2018-12-31 00:00:00"
lubridate::tz(a$date)
#> [1] ""
View(lubridate::olson_time_zones())
#> Warning: 'olson_time_zones' is deprecated; use 'OlsonNames' instead. Deprecated
#> in version '1.5.6'.
lubridate::tz(a$date) = "Europe/London"
lubridate::tz(a$date)
#> [1] "Europe/London"
```

<sup>Created on 2020-01-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment]
Just noticed, the `time` variable does not seem to have a date-time class which is something we should fix if not...

**Comment by markruddy** [comment]
Setting tz (in `lubridate` or using `POSIXct`) should be fine. I'll be playing about with this over the coming days so I'll post back when I've done some checking/testing of the timezone.

In general I do this that `stats19` should at least offer dates and times in those classes.

**Comment by Robinlovelace** [comment]
Good stuff @markruddy please do report back and, if you're feeling keen, a PR, e.g. here, would be welcome: 

https://github.com/ropensci/stats19/blob/ec76dd9ed1c4bda6f7b415d71bf5fdfce70cb28c/R/format.R#L71

We could format the `time` column in the same way.

**Comment by Robinlovelace** [comment]
https://github.com/ropensci/stats19/blob/ec76dd9ed1c4bda6f7b415d71bf5fdfce70cb28c/R/format.R#L71-L73

**Comment by Robinlovelace** [comment]
Update: R doesn't have a native class for time of day: https://stackoverflow.com/questions/19460608/want-only-the-time-portion-of-a-date-time-object-in-r

https://github.com/tidyverse/hms has a class for it but would rather NOT add another dependency.
Therefore, I think, the best solution is to add a datetime variable.

**Comment by Robinlovelace** [comment]
Heads-up @markruddy, @layik and @agila5, I think the latest PR fixes this in a solid way, by creating the much needed datetime column no provided by DfT but which will be useful for researchers. Comments on #147 welcome.

**Comment by markruddy** [comment]
Looks like it does the trick! How timely. My only comment would be to conform to the [ISO 8601 date standard](https://www.iso.org/iso-8601-date-and-time-format.html) of YYYY-MM-DD. This will help prevent confusion between US MMDDYYYY and UK/rest of the world DDMMYYY. I could do a PR for this on #147.

**Comment by Robinlovelace** [comment]
I think the output of the `date` column is now in the ISO date standard. Can you try to reproduce the example below?:

``` r
# Aim: test date output from stats19 package
devtools::install_github("ropensci/stats19")
#> Skipping install of 'stats19' from a github remote, the SHA1 (15f1c4e4) has not changed since last install.
#>   Use `force = TRUE` to force installation
crashes_2018 = stats19::get_stats19(year = 2018, type = "accidents")
#> Files identified: dftRoadSafetyData_Accidents_2018.csv
#>    http://data.dft.gov.uk.s3.amazonaws.com/road-accidents-safety-data/dftRoadSafetyData_Accidents_2018.csv
#> Data already exists in data_dir, not downloading
#> Data saved at ~/stats19-data/dftRoadSafetyData_Accidents_2018.csv
#> Reading in:
#> ~/stats19-data/dftRoadSafetyData_Accidents_2018.csv
#> date and time columns present, creating formatted datetime column
head(crashes_2018$date)
#> [1] "2018-01-01" "2018-01-01" "2018-01-01" "2018-01-01" "2018-01-01"
#> [6] "2018-01-01"
```

<sup>Created on 2020-01-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by markruddy** [comment]
Apols for radio silence.

Example reproduced. Although, referring back to #147, it's strictly not a datetime variable but a date. Perhaps the formatting done whould aim for POSIXct, which combine date and time and includes timezones - important because it specifies the Daylight Saving Time in place within that time zone.

**Comment by Robinlovelace** [comment]
> Perhaps the formatting done whould aim for POSIXct, which combine date and time and includes timezones

Good suggestion @markruddy which has, I think, already been implemented thanks to your suggestions:

``` r
devtools::install_github("ropensci/stats19")
#> Skipping install of 'stats19' from a github remote, the SHA1 (6163bc29) has not changed since last install.
#>   Use `force = TRUE` to force installation
a = stats19::get_stats19(2018, "ac")
#> Files identified: dftRoadSafetyData_Accidents_2018.csv
#>    http://data.dft.gov.uk.s3.amazonaws.com/road-accidents-safety-data/dftRoadSafetyData_Accidents_2018.csv
#> Data already exists in data_dir, not downloading
#> Data saved at ~/stats19-data/dftRoadSafetyData_Accidents_2018.csv
#> Reading in:
#> ~/stats19-data/dftRoadSafetyData_Accidents_2018.csv
#> date and time columns present, creating formatted datetime column
class(a$date)
#> [1] "Date"
class(a$datetime)
#> [1] "POSIXct" "POSIXt"
lubridate::tz(a$datetime)
#> [1] "Europe/London"
```

<sup>Created on 2020-02-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Does that solve it for you?
