### ISSUE TITLE
Casualties and sf output format

### ISSUE THREAD

**Issue by agila5** [ropensci/stats19#155]
Another thing that I did not consider is the following:

``` r
# packages
library(stats19)
#> Data provided under OGL v3.0. Cite the source and link to:
#> www.nationalarchives.gov.uk/doc/open-government-licence/version/3/

get_stats19(2017, type = "casualties", output_format = "sf")
#> Files identified: dftRoadSafetyData_Casualties_2017.zip
#>    http://data.dft.gov.uk.s3.amazonaws.com/road-accidents-safety-data/dftRoadSafetyData_Casualties_2017.zip
#> Attempt downloading from:
#> Data saved at /tmp/RtmpU0Y2L0/dftRoadSafetyData_Casualties_2017/Cas.csv
#> 0 rows removed with no coordinates
#> Warning: Length of logical index must be 1 or 170993, not 0
#> Error in getClassDim(rep(0, length(coords)), length(coords), dim, "POINT"): 0 is an illegal number of columns for a POINT
```

<sup>Created on 2020-02-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The problem occurs here
https://github.com/ropensci/stats19/blob/f9982ed8fed2f235c014d648202ea050ce2ee1f2/R/get.R#L171-L179
since it doesn't make sense to use `format_sf` for casualities. Should I create a test for this case and create and informative error message?

**Comment by Robinlovelace** [comment]
I think a message and returning a data frame would be the best option. Well spotted!
