### ISSUE TITLE
Pkgdown build is failing

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stats19#158]
Heads-up @jeroen, I think this is due to upstream changes in GDAL/PROJ that you are aware of. Details: https://dev.ropensci.org/blue/organizations/jenkins/stats19/detail/stats19/162/pipeline

I don't think immediate action is needed, this is more of a heads-up. Could be useful to know which versions of GDAL and PROJ is the Jenkins CI system using.

**Comment by Robinlovelace** [comment]
Fixed by upstream fixes in PCT package, which now returns objects with a properly formatted CRS in `sf`.

**Comment by layik** [comment]
I see.
