### ISSUE TITLE
packagedown build fail

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stats19#179]
Heads-up @jeroen, it seems the Jenkins build process is failing for some reason: https://dev.ropensci.org/job/stats19/233/display/redirect

Not sure how to debug this one, any ideas?

**Comment by jeroen** [comment]
Ooops sorry I upgraded the server and forgot to restart docker... thanks for noticing! Should be fixed now.

**Comment by Robinlovelace** [comment]
Good fix @jeroen, good comms. Great to see a new badge also, but what does it mean?

![image](https://user-images.githubusercontent.com/1825120/100271046-bf66b300-2f50-11eb-9556-42b97edfaa05.png)

**Comment by jeroen** [comment]
It's a new thing I'm working on 😄
