### ISSUE TITLE
Suport spatstat 2.0 packages

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stats19#191]
See here for context: https://github.com/rubak/spatstat.revdep/blob/main/README.md

It's now failing checks as a result of these upstream changes in `spatstat`. Heads-up @agila5 and @layik I'm on it!

https://win-builder.r-project.org/incoming_pretest/stats19_1.4.0_20210301_011923/Windows/00check.log

**Comment by agila5** [comment]
Hi @Robinlovelace! I added the code for spatstat so, if you want, I can work on this problem today in the afternoon!

**Comment by Robinlovelace** [comment]
Thanks Andrea! Can you take a look at the PR: https://github.com/ropensci/stats19/pull/192

**Comment by agila5** [comment]
Sure, first thing after lunch!

**Comment by Robinlovelace** [comment]
OK. I've finished my work on the PR now. Bets that tests will pass: :crossed_fingers:  but wouldn't bet money on it! Over to you, any further changes to that PR v welcome.

**Comment by Robinlovelace** [comment]
Update @agila5 because it was passing locally PR checks seem to be failing on GH Actions I merged the PR. So please tack a look at what I've changed on `master`. Any further changes welcome before I submit `stats19` 1.4.0 to CRAN.

**Comment by Robinlovelace** [comment]
Closing because I think it's fixed.

**Comment by agila5** [comment]
Hi Robin! I have just a couple of comments. While reading the spatstat guide for updating, I noticed that they report: 

> We strongly recommend that you
> DO NOT submit your updated package to CRAN yet
> DO help us by adding spatstat (>= 2.0-0) to Imports/Depends/Suggests as detailed below even if it isn’t strictly necessary.

Hence, I think that we should 1) add the version dependency to spatstat and 2) wait a couple of days before submitting the package to CRAN (or revert those changes, since atm spatstat 2.0.0 is not on CRAN).

**Comment by Robinlovelace** [comment]
> Hence, I think that we should 1) add the version dependency to spatstat and 2) wait a couple of days before submitting the package to CRAN (or revert those changes, since atm spatstat 2.0.0 is not on CRAN).

Sounds good but isn't that date a bit out of date? In any case it's worth waiting a few days for sure :+1:
