### ISSUE TITLE
Final changes before release

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stats19#195]
Are there any changes to the NEWS or anything we should make before releasing the latest version? Heads-up @agila5 I submitted this to build on 'win-devel' and only got this error message:

   URL: https://www.tidyverse.org/lifecycle/ (moved to
https://lifecycle.r-lib.org/articles/stages.html)
       From: README.md
       Status: 200
       Message: OK

**Comment by agila5** [comment]
> Are there any changes to the NEWS or anything we should make before releasing the latest version?

IMO no. If you submit the existing code after spatstat 2.0.0 is on CRAN, maybe we can add a note saying that `stats19` now requires a version of `spatstat` greater or equal than 2.0.0. I think that's the only important change for any user (since the other changes are just related to URLs and eval = FALSE in the vignette, right?)

**Comment by Robinlovelace** [comment]
Good point, I'll keep my eyes on https://cran.r-project.org/web/packages/spatstat/index.html

**Comment by agila5** [comment]
btw: I think that there are just a handful of people worldwide that use the `spatstat` interface in `stats19`, so I think that if there is any time pressure you can easily comment out or delete the spatstat code.

**Comment by Robinlovelace** [comment]
Or just submit it now - in fact the dependency is on `spatstat.geom` >- 2.0.0.

**Comment by agila5** [comment]
> Or just submit it now - in fact the dependency is on spatstat.geom >- 2.0.0.

👍, then we can change that later if there are problems with the dependencies

**Comment by Robinlovelace** [comment]
Just submitting it :+1:
