### ISSUE TITLE
Two issues

### ISSUE THREAD

**Issue by wengraf** [ropensci/stats19#202]
Hi: two things I've fixed (I've made a pull request).  Firstly, I am finding the **TfL API is giving out wrong information** (based on a very old version of the dataset?), so I've added a warning.  Secondly, I realised that with get_MOT(), if you have a list of made solely of new cars (in other words, pre-first-MOT), the function crashed (as they've no mileage data).  So I've fixed that.

**Comment by Robinlovelace** [comment]
Closed in #201
