### ISSUE TITLE
Add API interface when it comes online

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stats19#51]
This is a placeholder. DfT are planning to add an API to enable interactive access to STATS19 data. We will add an interface to this when it's ready for testing (likely on a test branch to start with), perhaps with a new functions such as:

```r
dl_stats19_api = function(year, type, bbox, ...) {
  ...
}
```

The arguments will likely change depending on the api.

**Comment by layik** [comment]
Meant to close this one. We will be creating a bunch of issues once this comes a live including reopening this maybe.
