### ISSUE TITLE
news for latest CRAN version?

### ISSUE THREAD

**Issue by sckott** [ropensci/stats19#90]
Seems there's no news or release notes for the most recent CRAN version.

**Comment by Robinlovelace** [comment]
Good point @sckott I forgot to update the version number in the NEWS.md file! Should I submit a patch version to CRAN or leave as is this time?

**Comment by sckott** [comment]
nah, just like to remind people when I see missing news :)

**Comment by Robinlovelace** [comment]
Great - and I just realised you were talking about note here https://github.com/ropensci/stats19/releases/tag/0.2.0

Thanks for the reminder!
