### ISSUE TITLE
Make/Model files not available

### ISSUE THREAD

**Issue by gacolitti** [ropensci/stats19#94]
Are the files in `file_names` current? Make/model files don't appear to exist.

````
require(stats19)
get_stats19(year = 2015, file_name = "MakeModel2015.zip")
````

**Comment by Robinlovelace** [comment]
Thanks for raising the issue. I see this issue also:

```
stats19::dl_stats19(year = 2015, "model")
Files identified: MakeModel2015.zip

   http://data.dft.gov.uk.s3.amazonaws.com/road-accidents-safety-data/MakeModel2015.zip
Good to go (y = enter, n = N/other)? y
Attempt downloading from: 
trying URL 'http://data.dft.gov.uk.s3.amazonaws.com/road-accidents-safety-data/MakeModel2015.zip'
Error in utils::download.file(zip_url, destfile = destfile) : 
  cannot open URL 'http://data.dft.gov.uk.s3.amazonaws.com/road-accidents-safety-data/MakeModel2015.zip'
In addition: Warning message:
In utils::download.file(zip_url, destfile = destfile) :
  cannot open URL 'http://data.dft.gov.uk.s3.amazonaws.com/road-accidents-safety-data/MakeModel2015.zip': HTTP status was '403 Forbidden'
```

To clarify: which files would you expect to download?

**Comment by gacolitti** [comment]
I don't see the make/model files anymore at https://data.gov.uk/dataset/cb7ae6f0-4be6-4935-9277-47e5ce24a11f/road-safety-data. I emailed the DfT team asking why the make/model files have been removed and am awaiting a response. I'm bringing up this issue here because I would like to get clarification on how `file_names` is generated. I thought it gets the file names for currently available files. Maybe the files available on the website above differ from the files you are pulling from the AWS server.

**Comment by Robinlovelace** [comment]
Hi @gacolitti thanks for reporting this. The urls were generated by a script that does not auto-update. I think it may be time to update them! You up for giving it a shot @layik ? Interesting that they seem to be removed. Keep us posted.

**Comment by gacolitti** [comment]
I’ve received confirmation that the make/model files have been removed because of privacy concerns.

**Comment by Robinlovelace** [comment]
Should be removed from the files that can be downloaded then. Thanks for the follow-up.

**Comment by Robinlovelace** [comment]
https://github.com/geekamit/mongodb-clinic
