### ISSUE TITLE
Highlight/add/mention "contributory factors"

### ISSUE THREAD

**Issue by layik** [ropensci/stats19#95]
- [x] where is the data? Is it in `stats19`? Answer: not in accidents, vehicles or casualties.
- [ ] mention it somewhere
- [ ] if not included already, if feasible and suitable to add functions to the package to obtain it.

https://www.gov.uk/government/statistical-data-sets/ras50-contributory-factors

**Comment by layik** [comment]
1. RAS50013: [Reported road casualties resulting from accidents, by contributory factor, region and country, Great Britain (ODS, 183KB)](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/743107/ras50013.ods)

2. RAS50016: [Reported accidents where a police officer attended the scene, by contributory factor, local authority and region, Great Britain (ODS, 342KB) ](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/743109/ras50016.ods)

**Comment by layik** [comment]
Current state, and it hopefully will change, this looks like fit for a Vignette rather than functions. Unless, we include the data within the package and release it. Please voice your experience/suggestions.

**Comment by Robinlovelace** [comment]
Sounds sensible, good data researching @layik. See you soon in LIDA to discuss.

**Comment by layik** [comment]
Deferred for now, reopen when ready. Cleaning issues.
